### ISSUE TITLE
Build failure when upgrading to 0.8.0

### ISSUE THREAD

**Issue by systemride** [sAleksovski/react-native-android-widget#40]
We are using:
react-native: 0.71.8 (not expo)
gradle: 7.5.1

I am able to build successfully on `0.6.1` and even `0.7.0` but when trying to build `0.8.0` I get the following errors:

```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
(appdir)/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/RNWidgetConfigurationActivity.java:53: error: method does not override or implement a method from a supertype
            @Override
            ^
Note: (appdir)/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/RNWidgetCollectionService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-android-widget:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

**Comment by sAleksovski** [comment]
Hi,

I just released [`0.8.1`](https://github.com/sAleksovski/react-native-android-widget/releases/tag/v0.8.1) which should be compatible with React Native 71.
Can you try it?
